config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :posts, only: [:new, :create] do
    resources :comments, only: [:create]
  end
  resource :user_session, only: [:new, :create, :destroy]
  resource :user, only: [:update, :edit, :new, :create]
  resources :users do
    resources :posts, only: [:index, :show]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :author, class_name: "User"

  default_scope { order('created_at DESC') }

  validates :author, :body, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :posts
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  mount_uploader :image, ImageUploader

  belongs_to :author, class_name: "User"
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :comments

  validate :all_tags_are_valid
  validates :author, :body, :title, presence: true

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create
    end
  end

  def all_tags
    self.tags.pluck(:name).join(", ")
  end

  private

  def all_tags_are_valid
    errors.add(:all_tags, "Can't contain special characters") unless tags.all? {|t| t.valid? }
  end

  scope :published, -> { where('published_at <= ?', Time.now) }
  scope :unpublished, -> { where('published_at IS NULL') }

  def publish!
    self.published_at = Time.now
    self.save!
  end

  def draft?
    self.published_at.nil?
  end

  def title_with_status
    if self.draft?
      self.title = "#{title} [DRAFT]"
    else
      self.title = "#{title}"
    end
  end

  def normalize_friendly_id(title)
    super.gsub("-", "_")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  validates :name, presence: true, format: { without: /[^\w-]/ }, length: { in: 2..50 }




end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  extend FriendlyId
  friendly_id :username, use: :finders

  has_many :posts, foreign_key: :author_id
  has_many :comments

  validates :email, :name, :username, presence: true
  validates :name, :username, length: { minimum: 3 }
  validates :email, format: { with: /.+@.+\..+/, message: "must be an email address" }, uniqueness: true
  validates :username, uniqueness: true
  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/, message: "can't have whitespace or special characters" }
  validates :password, confirmation: true
  validates :password, :password_confirmation, presence: { on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def not_authenticated
    redirect_to root_path, alert: "You do not have permission to access that page."
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.author = current_user
    if @comment.save
      redirect_to user_post_path(@post.author, @post), notice: "Your comment has been published"
    else
      flash.alert = "Your comment could not be published. Please correct the errors below."
      render "posts/show"
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post
  before_action :load_user, except: [:new, :create]
  before_action :require_login, except: [:index, :show]

  def index
    @posts = @user.posts.order("created_at").page(params[:page]).per(PER_PAGE)
    unless @user == current_user
      @posts = @posts.published
    end
  end

  def create
    @post.author = current_user
    if @post.save
      if params[:commit] == "Save As Draft"
        message = "Your draft has been saved."

      else
        message = "Your knowledge has been published."
        @post.publish!
      end
      redirect_to user_posts_path(current_user), notice: message

    else
      flash.alert = "Your knowledge could not be published. Please correct the errors below."
      render :new
    end
  end

  def show
    if @post.draft? && @post.author != current_user
      flash.alert = "You do not have permission to access that page."
      redirect_to root_path
    end
    @comments = @post.comments.all
    @comment = Comment.new
  end

  private


  def load_post
    if params[:id].present?
      @post = Post.find(params[:id])

    else
      @post = Post.new
    end

    if params[:post].present?
      @post.assign_attributes(post_params)
    end
  end

  def load_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :all_tags)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:user][:email], params[:user][:password])
      redirect_to root_path, notice: "Welcome back, #{@user.name}"
    else
      @user = User.new(email: params[:user][:email])
      flash.alert = "We could not sign you in. Please check your email/password and try again."
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "You have been signed out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :edit, :update]

  def index
    @users = User.order("name").page(params[:page]).per(PER_PAGE)
  end

  def edit
    if !current_user
      redirect_to root_path
    else
       @user = current_user
    end
  end

  def create
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      auto_login(@user)
      redirect_to root_path, notice: "Welcome, #{@user.name}"
    else
      flash.alert = "Please fix the errors below to continue."
      render :new
    end
  end

  def update
    @user = current_user
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to user_posts_path(@user)
      flash.notice = "Your profile has been updated"
    else
      flash.alert = "Please fix the errors below to continue"
      render :edit
    end
  end

  protected

  def load_user
    if params[:id].present?
      @user = User.find(params[:id])
    else
      @user = User.new
    end
    if params[:user].present?
      @user.assign_attributes(user_params)
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :bio, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #This method generates a "gravatar id" from the user email (all in lowercase per gravatar rules"
  #It then creates a url where that gravatar can be found
  #Following that, a image tag is created which upon render displays that gravatar image.
  #To user, just call this method on a user view.
  #See:
  #asciicasts.com/episodes/244-gravatar
  #Only addition is using the image tag within the method
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt:user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Median
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600,700,300' rel='stylesheet' type='text/css'>
  %body
    #container
      %nav
        %ul
          %li= link_to "Median", root_path
          - if !logged_in?
            - unless controller_name == "users" && action_name != "index"
              %li= link_to "Sign Up", new_user_path
            - unless controller_name == "user_sessions"
              %li= link_to "Sign In", new_user_session_path
          - else
            %li= link_to "Share Some Knowledge", new_post_path
            %li#link_user= link_to "#{current_user.name}", user_posts_path(current_user)
            %li#edit_user= link_to "Edit", edit_user_path
            %li#sign_out= link_to "Sign Out", user_session_path, method: :delete
      - background_image = @post ? @post.image_url.to_s : ""
      %header{ :style => "background-image: url('#{background_image}')"}
        = content_for?(:page_title) ? content_for(:page_title) : "Page Title"
      %section#content
        - flash.each do |key, message|
          %div{ class: "flash-#{key}" }= message
        %article= yield
      %footer
        %p This is the #{link_to "Nashville Software School", "http://nashvillesoftwareschool.com"} Cohort 8 Class Project / Medium clone.
        = link_to "View the code on Github", "https://github.com/elizabrock/median"

app/views/posts/index.html.haml
- content_for(:page_title) do
  %h1 Welcome to #{@user.name}

%div.profile-container
  =gravatar_for @user
  %h2 #{@user.name}
  %p #{@user.bio}


= paginate @posts

%ul.posts-pagination
  - @posts.each do |post|
    %li= link_to post.title_with_status, user_post_path(post.author, post)

= link_to "< All Contributors", root_path

app/views/posts/new.html.haml
- content_for(:page_title) do
  %h1 Share New Knowledge

= simple_form_for @post, :html => {:multipart => true} do |f|
  = f.input :title
  = f.input :body
  = f.input :all_tags, label: "Tags", placeholder: "Tags separated with commas"
  = f.input :image, label: "Upload an image", hint: "For best results, choose an image that's at least 400 pixels wide and at least 150 pixels tall."
  = f.button :submit, "Save As Draft"
  = f.button :submit, "Publish Knowledge"

app/views/posts/show.html.haml
- content_for(:page_title) do
  %h1= @post.title_with_status
  .author
    By:
    = @post.author.name
:markdown
  #{@post.body}
  #####Tags
  #{@post.all_tags}

= link_to "Return to #{@post.author.name}'s Knowledgeable", user_posts_path(@post.author)

%hr

%div.comments#comments
  %h2.comments-heading Comments
  - if logged_in?
    %div.comment-form
      %h3.comment-form-heading Leave a comment
      = simple_form_for [@post, @comment] do |f|
        = f.input :body, label: false
        = f.button :submit, "Publish Comment"

  - @post.comments.each do |comment|
    %div.comment
      %div.comment-meta
        = link_to "#{comment.author.name}", user_posts_path(comment.author)
        %span.timestamp= "#{time_ago_in_words(comment.created_at)} ago"
      %p.comment-body= comment.body

app/views/user_sessions/new.html.haml
- content_for(:page_title) do
  %h1 Sign In

= simple_form_for @user, url: user_session_path do |f|
  = f.input :email
  = f.input :password
  = f.button :submit, "Sign In"

app/views/users/edit.html.haml
- content_for(:page_title) do
  %h1 Edit Profile

= simple_form_for @user, url: user_path, method: :put do |f|
  = f.input :name
  = f.input :bio
  = f.input :email
  = f.button :submit, "Save Changes"

app/views/users/index.html.haml
- content_for(:page_title) do
  %h1 Welcome to Median!
  %p The world's newest Medium clone.

%h2 Our Knowledgeable Contributors:

= paginate @users

%ul.user_pagination
  - @users.each do |user|
    %li= link_to "#{user.name}'s Knowledge", user_posts_path(user)

app/views/users/new.html.haml
- content_for(:page_title) do
  %h1 Sign Up

= simple_form_for @user, url: user_path do |f|
  = f.input :name
  = f.input :bio
  = f.input :email
  = f.input :username
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit, "Sign Up"